<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->headTitle($this->title) ?>
<?php echo $this->plugin('HeadMeta');?>
<?php
echo $this->headLink()->prependStylesheet($this->dxConfig()->getStylesheetUrl('base_css.css', FALSE));
echo $this->plugin('HeadLink');
echo $this->headLink()->appendStylesheet($this->dxConfig()->getStylesheetUrl('style.css'));
echo $this->plugin('HeadStyle');
?>
<?php echo $this->headScript()->prependFile($this->dxConfig()->getBaseUrl('assets') . 'js/base_js.js');?>
<link rel="shortcut icon" href="<?php echo $this->dxConfig()->getImageUrl('dx/ico/favicon.ico', FALSE) ?>">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->dxConfig()->getImageUrl('dx/ico/apple-touch-icon-144-precomposed.png', FALSE) ?>">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->dxConfig()->getImageUrl('dx/ico/apple-touch-icon-114-precomposed.png', FALSE) ?>">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->dxConfig()->getImageUrl('dx/ico/apple-touch-icon-72-precomposed.png', FALSE) ?>">
<link rel="apple-touch-icon-precomposed" href="<?php echo $this->dxConfig()->getImageUrl('dx/ico/apple-touch-icon-57-precomposed.png', FALSE) ?>">