<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="/">Project Unknown</a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="/">Home</a></li>
					<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="/forsale">For Sale<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="/forsale">Browse Categories</a></li>
							<li><a href="/forsale/create">New Post</a></li>
						</ul>
					</li>
					<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="/tobuy">To Buy<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="/tobuy">Browse Categories</a></li>
							<li><a href="/tobuy/create">New Post</a></li>
						</ul>
					</li>
					<li><a href="/user/login">Login</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
							<li><a href="#">One more separated link</a></li>
						</ul>
					</li>

					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Links<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a target="_blank" href="http://framework.zend.com/learn">ZF2 Docs</a></li>
							<li><a target="_blank" href="http://framework.zend.com/zf2">ZF2 Dev Portal</a></li>
							<li><a target="_blank" href="http://modules.zendframework.com/">ZF2 Modules</a></li>
							<li><a target="_blank" href="https://github.com/zendframework/zf2">ZF2 on GitHub</a></li>
							<li><a target="_blank" href="http://www.phpdoc.org/docs/latest/index.html">phpDocumentor</a></li>
							<li class="divider"></li>
							<li><a target="_blank" href="http://docs.doctrine-project.org/en/latest/reference/working-with-associations.html">Doctrine Entity - Association</a></li>
							<li><a target="_blank" href="http://docs.doctrine-project.org/en/2.0.x/reference/tools.html">Doctrine Tools</a></li>
							<li><a target="_blank" href="http://www.zendcasts.com/many-to-many-with-doctrine-2/2011/03/">Doctrine - ZendCast</a></li>
							<li class="divider"></li>
							<li><a href="/tw-bootstrap-demo/form-horizontal">Horizontal</a></li>
							<li><a href="/tw-bootstrap-demo/form-vertical">Vertical</a></li>
							<li><a href="/tw-bootstrap-demo/form-inline">Inline</a></li>
							<li><a href="/tw-bootstrap-demo/form-search">Search</a></li>
							<li><a target="_blank" href="http://twitter.github.com/bootstrap/base-css.html#buttons">Bootstrap - Icons</a></li>
							<li class="divider"></li>
							<li><a target="_blank" href="http://gediminasm.org/article/tree-nestedset-behavior-extension-for-doctrine-2">GedMo Documents</a></li>
						</ul>
					</li>


				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>