<?php

$html = '';
$crumb = array(
	'url' => '/' . ($this->entityType == 'sell' ? 'forsale' : 'tobuy'),
	'title' => ($this->entityType == 'sell' ? 'For Sale Items' : 'To Buy Items'),
	'anchor' => ($this->entityType == 'sell' ? 'For Sale' : 'To Buy')
);
$this->dxBreadcrumb()->add(($this->entityType == 'sell' ? 'forsale' : 'tobuy'), $crumb);
$this->dxBreadcrumb()->add('New Ad', array('anchor' => 'New Ad'));

$html .= '<h1>Create a New Ad</h1>';
$form = $this->form;
$form->prepare();
if ($form->getMessages()):
	$this->dxAlert()->addError('<strong>Invalid Input!</strong> The form fields are not filled out correctly.');
endif;
$html .= $this->formTwb($form, $formType, $this->formDisplayOptions);
echo $html;